### ISSUE TITLE
TypeError: to_csv()

### ISSUE THREAD

**Issue by DyslexicMoment** [nicolaskruchten/jupyter_pivottablejs#1]
When I run `pivot_ui(df)` I get:
```
     72 def pivot_ui(df, outfile_path = "pivottablejs.html", width="100%", height="500"):
     73     with open(outfile_path, 'w') as outfile:
---> 74         outfile.write(template % df.to_csv("pivottablejs_data.csv"))
     75     return IFrame(src=outfile_path, width=width, height=height)
     76 

TypeError: to_csv() takes at least 2 arguments (1 given)
```
I tried specifying a filename for to_csv() but it returned to same error. `outfile.write(template % df.to_csv("pivottablejs_data.csv"))`

I tried this with my notebook and with the mtl311 data.

Versions
Python: 2.7.6
IPython: 3.1.0
Pandas: 0.13.1

**Comment by nicolaskruchten** [comment]
The issue is that `to_csv` has changed signature between Pandas 0.13.1 and Pandas 0.16.2 (which is the current stable version)... In the version you are using, `to_csv` writes a file and requires additional arguments. In the latest version, `to_csv` returns a string when you call it without arguments.

See http://pandas.pydata.org/pandas-docs/version/0.13.1/generated/pandas.DataFrame.to_csv.html vs http://pandas.pydata.org/pandas-docs/version/0.16.2/generated/pandas.DataFrame.to_csv.html
